### ISSUE TITLE
请问下miao联机的账号注册网站什么时候能访问

### ISSUE THREAD

**Issue by eliyahgan** [CelesteNyaServer/CelesteMiaoServer.Wiki#35]
“（目前网站的登录功能还在维护中，暂不可使用）”
感谢大大的工作！
我是从B站视频一路过来的（https://www.bilibili.com/video/BV1af4y1f759?p=3
我看8月份的评论就有人反映网页不能访问，不能注册账号，也就不能联机，现在已经10月份了，所以来问一下服务器后续还会开吗

**Comment by Small-Miao** [comment]
我也很想快速恢复访问
但是上次功能的打击对我其实挺大的,作为一个免费的服务器 我的服务被人攻击到瘫痪。
我也不知道攻击者是出于什么样的目的,这个打击对我还是比较大的 因为我铺垫的一部分东西全部丢失了
因为我已经成功创建了一个地图通关数据库等东西 但是,由于这次攻击被彻底数据全部丢失了。我需要从头慢慢来进行开发。
优化啊 新的界面 更完善的社区等等 所以 慢慢等吧 我如果努努力 可能会在2023年的大年三十前正式恢复吧

**Comment by eliyahgan** [comment]
您好，您发送的邮件我已经收到，我会在仔细阅读后尽快给予答复，谢谢。    罗淦Hello,thank you for your e-mail.And l will  handle it as soon as possible after carefully reading.    LuoGan

**Comment by eliyahgan** [comment]
很遗憾知道过去发生的事情，很难想象攻击者出于什么目的攻击服务器的。
丢失的东西一定花费了你许多的激情和时间，令人难过的不是千难万阻，而是从头再来。
希望未来某天，你能从那次打击中恢复过来。因为玩蔚蓝时，临近终点的失败，不会让我感到沮丧，而是让我坚信我离终点越来越近，第二次会更加熟练，
（如果有足够的时间和技术我也很愿意参加社区工作，可惜目前两样都不太有，或许未来能有机会 😂
